
INSERT INTO DB_DRONE (SN, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('A000091', 'MIDDLE_WEIGHT', 500, 30, 'LOADED');
INSERT INTO DB_DRONE (SN, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('A000092', 'MIDDLE_WEIGHT', 500, 40, 'LOADED');
INSERT INTO DB_DRONE (SN, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('A000093', 'MIDDLE_WEIGHT', 500, 35, 'IDLE');
INSERT INTO DB_DRONE (SN, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('A000094', 'MIDDLE_WEIGHT', 500, 80, 'IDLE');
INSERT INTO DB_DRONE (SN, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('A000095', 'MIDDLE_WEIGHT', 500, 80, 'IDLE');

INSERT INTO DB_MEDICATION(NAME, WEIGHT, CODE, IMAGE_URL, DRONE_ID) VALUES ('Paracetamol', 100, 'PARA705', 'https://www.drugs.com/images/pills/fio/IPL01901/paracetamol.JPG', 1);
INSERT INTO DB_MEDICATION(NAME, WEIGHT, CODE, IMAGE_URL, DRONE_ID) VALUES ('Ibuprofen', 150, 'IBU2500', 'https://www.drugs.com/images/pills/nlm/597623720.jpg', 2);

